import Head from "next/head";
import Avatar from "../components/avatar";
import {
  ViewGridIcon,
  SearchIcon,
  MicrophoneIcon,
} from "@heroicons/react/solid";
import Image from "next/image";
import Footer from "../components/footer";
import { useRef } from "react";
import { useRouter } from "next/router";
import Link from 'next/link';

export default function Home() {
  const searchInputRef = useRef(null);
  const router = useRouter();

  const search = (e) => {
    e.preventDefault();
    const term = searchInputRef.current.value;

    if (!term) {
      return;
    }

    router.push("https://google.com/search?q=" + term);
  };
  
  return (
    <div className="flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}
      <header className="flex w-full p-4 pt-3 justify-between text-sm text-gray-800">
        {/* left */}
        <div className="flex space-x-4 items-center ml-2">
          <div>
            <Link href="https://about.google/?fg=1&utm_source=google-US&utm_medium=referral&utm_campaign=hp-header">
              <p className="link">About</p>
            </Link>
          </div>
          <div>
            <Link href="https://store.google.com/US?utm_source=hp_header&utm_medium=google_ooo&utm_campaign=GS100042&hl=en-US">
              <p className="link">Store</p>
            </Link>
          </div>
          
        </div>

        {/* right */}
        <div className="flex space-x-4 items-center text-xs">
          <div>
            <Link href="https://mail.google.com/mail/?authuser=0&ogbl">
              <p className="link">Gmail</p>
            </Link>
          </div>
          <div>
            <Link href="https://www.google.com/imghp?hl=en&authuser=0&ogbl">
              <p className="link">Images</p>
            </Link>
          </div>
          
          {/* icon */}
          <div>
            <Link href="https://workspace.google.com/marketplace?pann=ogb">
              <ViewGridIcon className="h-9 w-9 p-2 rounded-full text-gray-500 hover:bg-gray-100 cursor-pointer"></ViewGridIcon>
            </Link>
          </div>
          

          {/* profile pic */}
          <Avatar url="https://i0.wp.com/hipradar.net/wp-content/uploads/2018/05/usain-bolt.jpg?fit=1200%2C749&ssl=1"></Avatar>
        </div>
      </header>

      {/* body */}
      <form className="flex flex-col items-center mt-16 flex-grow w-3/4">
        <Image className="object-cover"
          src="/logo.png"
          height={100}
          width={350}
        ></Image>

        <div className="flex w-full mt-5 hover:shadow-lg focus-within:shadow-lg max-w-md rounded-full border border-gray-300 px-5 py-2 items-center sm:max-w-xl">
          <SearchIcon className="h-5 mr-3 pl-0 ml-0 text-gray-400"></SearchIcon>

          <input ref={searchInputRef} type="text" className="focus:outline-none flex-1"></input>

          <MicrophoneIcon className="h-5 text-gray-500 hover:cursor-pointer"></MicrophoneIcon>
        </div>

        <div className="flex flex-col w-50% space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button onClick={search} className="btn">Google Search</button>
          <button onClick={search} className="btn">I'm Feeling Lucky</button>
        </div>
      </form>

      {/* footer */}
      <Footer/>
    </div>
  );
}
